#!/usr/bin/env bash
# This Script installs GPIOzero on the Raspberry Pi
#sudo apt update -y
if [ "$1" = "3" ]; then
   sudo apt install python3-gpiozero -y
fi
if [ "$1" = "2" ]; then
   sudo apt install python-gpiozero -y
fi
